name: HubManager
main: me.creepysin.hubmanager.Main
version: 1.3
api-version: 1.14
author: Creepysin
website: https://github.com/Creepysin/HubManager
description: Provides the ablity to add hubs using commands such as '/hub'
commands:
  sethub:
    description: Sets the hub
    usgae: /<command>
    permission: hubmanager.sethubs
  hubmanager:
    description: Hubmanager commands
    usgae: /<command>
  hubs:
    description: Gets all hubs
    usgae: /<command>
    permission: hubmanager.hubs