name: HubManager
main: org.australiacraft.hubmanager.Main
version: 0.1.3
author: Australiacraft Team
authors: [Creepysin]
website: https://github.com/australiacraft/HubManager
commands:
  sethub:
    description: Sets the hub
    usgae: /<command>
    permission: hubmanager.sethubs
  hubmanager:
    description: Hubmanager commands
    usgae: /<command>