name: BasicUtils
main: org.australiacraft.bukkit.Main
version: 0.1
author: Creepysin
website: https://github.com/australiacraft/BasicUtils
commands:
  hub:
    description: Tps you to the hub
    usage: /<command>
  sethub:
    description: Sets the hub
    usgae: /<command>