name: HubManager
main: org.australiacraft.hubmanager.Main
version: 1.0
api-version: 1.14
author: Australiacraft Team
authors: [Creepysin]
website: https://github.com/australiacraft/HubManager
commands:
  sethub:
    description: Sets the hub
    usgae: /<command>
    permission: hubmanager.sethubs
  hubmanager:
    description: Hubmanager commands
    usgae: /<command>
  hubs:
    description: Gets all hubs
    usgae: /<command>
    permission: hubmanager.hubs